kind: Deployment
apiVersion: apps/v1
metadata:
  name: multus-http
  namespace: multus1
  labels:
    app: multus-http
    app.kubernetes.io/instance: multus-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multus-http
  template:
    metadata:
      name: multus-http
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{ "name": "ipvlan-1085", "default-route": ["10.6.85.1"]} ]'
      labels:
        app: multus-http
    spec:
      containers:
        - name: httpd
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          image: 'image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest'
        - name: cli
          image: 'image-registry.openshift-image-registry.svc:5000/openshift/cli:latest'
          command:
          - sh
          - '-c'
          - tail -f /dev/null
      nodeSelector:
        kubernetes.io/hostname: ocp1-bm4nq-worker-wmpwz
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: multus-http
  namespace: multus2
  labels:
    app: multus-http
    app.kubernetes.io/instance: multus-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multus-http
  template:
    metadata:
      name: multus-http
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{ "name": "ipvlan-1085", "default-route": ["10.6.85.1"]} ]'
      labels:
        app: multus-http
    spec:
      containers:
        - name: httpd
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          image: 'image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest'
        - name: cli
          image: 'image-registry.openshift-image-registry.svc:5000/openshift/cli:latest'
          command:
          - sh
          - '-c'
          - tail -f /dev/null
      nodeSelector:
        kubernetes.io/hostname: ocp1-bm4nq-worker-zqffn
