apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: tenant1085
  namespace: openshift-ingress-operator
spec:
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/worker: ''
  domain: tenant1085.ocp1.redhat.hpecic.net
  tuningOptions: {}
  clientTLS:
    clientCA:
      name: ''
    clientCertificatePolicy: ''
  unsupportedConfigOverrides: null
  httpErrorCodePages:
    name: ''
  namespaceSelector:
    matchLabels:
      tenant: tenant1085
  replicas: 1
  httpEmptyRequestsPolicy: Respond
  endpointPublishingStrategy:
    loadBalancer:
      scope: External
    type: LoadBalancerService
