apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: AssignMetadata
metadata:
  name: force-tenant-label-in-namespaces
spec:
  location: metadata.labels.tenant
  match:
    kinds:
      - apiGroups:
          - '*'
        kinds:
          - Namespace
    namespaceSelector:
      matchExpressions:
        - key: tenant
          operator: DoesNotExist
    scope: Cluster
  parameters:
    assign:
      value: none
