apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper
metadata:
  name: gatekeeper
spec:
  audit:
    auditChunkSize: 66
    auditFromCache: Enabled
    auditInterval: 10s
    constraintViolationLimit: 55
    emitAuditEvents: Enabled
    logLevel: INFO
    replicas: 1
    resources:
      limits:
        cpu: 10
        memory: 20Gi
      requests:
        cpu: 100m
        memory: 20Mi
  mutatingWebhook: Enabled
  validatingWebhook: Enabled
  webhook:
    emitAdmissionEvents: Enabled
    failurePolicy: Fail
    logLevel: INFO
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - openshift
            - openshift-adp
            - openshift-apiserver
            - openshift-apiserver-operator
            - openshift-authentication
            - openshift-authentication-operator
            - openshift-cloud-controller-manager
            - openshift-cloud-controller-manager-operator
            - openshift-cloud-credential-operator
            - openshift-cloud-network-config-controller
            - openshift-cluster-csi-drivers
            - openshift-cluster-machine-approver
            - openshift-cluster-node-tuning-operator
            - openshift-cluster-samples-operator
            - openshift-cluster-storage-operator
            - openshift-cluster-version
            - openshift-config
            - openshift-config-managed
            - openshift-config-operator
            - openshift-console
            - openshift-console-operator
            - openshift-console-user-settings
            - openshift-controller-manager
            - openshift-controller-manager-operator
            - openshift-dns
            - openshift-dns-operator
            - openshift-dr-system
            - openshift-etcd
            - openshift-etcd-operator
            - openshift-gatekeeper-system
            - openshift-gitops
            - openshift-host-network
            - openshift-image-registry
            - openshift-infra
            - openshift-ingress
            - openshift-ingress-canary
            - openshift-ingress-operator
            - openshift-insights
            - openshift-kni-infra
            - openshift-kube-apiserver
            - openshift-kube-apiserver-operator
            - openshift-kube-controller-manager
            - openshift-kube-controller-manager-operator
            - openshift-kube-scheduler
            - openshift-kube-scheduler-operator
            - openshift-kube-storage-version-migrator
            - openshift-kube-storage-version-migrator-operator
            - openshift-kubevirt-infra
            - openshift-local-storage
            - openshift-machine-api
            - openshift-machine-config-operator
            - openshift-marketplace
            - openshift-monitoring
            - openshift-multus
            - openshift-network-diagnostics
            - openshift-network-operator
            - openshift-nfd
            - openshift-nmstate
            - openshift-node
            - openshift-nutanix-infra
            - openshift-oauth-apiserver
            - openshift-openstack-infra
            - openshift-operator-lifecycle-manager
            - openshift-operators
            - openshift-ovirt-infra
            - openshift-pipelines
            - openshift-route-controller-manager
            - openshift-sdn
            - openshift-serverless
            - openshift-service-ca
            - openshift-service-ca-operator
            - openshift-storage
            - openshift-terminal
            - openshift-user-workload-monitoring
            - openshift-vsphere-infra
            - openshift-workspaces
            - open-cluster-management
            - open-cluster-management-agent
            - open-cluster-management-agent-addon
            - open-cluster-management-global-set
            - open-cluster-management-hub
            - open-cluster-management-observability
            - kube-node-lease
            - kube-public
            - kube-system
    replicas: 3
