apiVersion: constraints.gatekeeper.sh/v1beta1
kind: TenantPolicy
metadata:
  name: tenant-policy
spec:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["networking.k8s.io"]
        kinds: ["NetworkPolicy"]
